workflows:
  ios-debug-build:
    name: iOS Debug Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Flutter clean
        script: flutter clean
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Set iOS minimum version
        script: sed -i '' 's/platform :ios, .*/platform :ios, '\''13.0'\''/' ios/Podfile
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Build iOS debug
        script: flutter build ios --debug
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/**/*.dSYM
    publishing:
      email:
        recipients:
          - billxdpro@gmail.com
