platform :ios, '13.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_install_all_ios_pods(flutter_application_path)
  plugins_file = File.join(flutter_application_path, '.flutter-plugins')
  deps_file = File.join(flutter_application_path, '.flutter-plugins-dependencies')

  if File.exist?(deps_file)
    eval(File.read(deps_file), binding)
  else
    puts "⚠️ Archivo .flutter-plugins-dependencies no encontrado, ejecuta 'flutter pub get' primero."
  end
end

target 'Runner' do
  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
end